version: '3.1'
services:
  intes_db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    networks:
      - intes
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: INTES
networks:
  intes: